### ISSUE TITLE
Оформление разделов (глав)

### ISSUE THREAD

**Issue by VadiRybin** [rominf/latex-g7-32#105]
Доброго времени суток!
В моём учебном заведении существуют собственные требования к оформлению ВКР. В частности оформление названия главы должно выглядеть следующим образом:

ГЛАВА {номер главы}
{НАЗВАНИЕ ГЛАВЫ}

Уже несколько дней потратил на поиск решения, однако ни на отечественных, ни на зарубежных ресурсах не нашел  информации каким образом можно установить такой формат отображения раздела.
Помогите пожалуйста, я в тупике.

**Comment by einhander** [comment]
Посмотрите пакет titlesec, он уже используется в стиле. Если будет непонятно, пишите дам пример.

**Comment by einhander** [comment]
Как понимаю вопрос решен.
