### ISSUE TITLE
Подпись ПРИЛОЖЕНИЕ в оглавлении

### ISSUE THREAD

**Issue by Echobana** [rominf/latex-g7-32#108]
Что нужно дописать в G2-105.sty чтобы в оглавлении перед буквой стояла подпись ПРИЛОЖЕНИЕ? Да и где в принципе прописано как устроена структура приложения, по ГОСТу нужно чтобы было написано ПРИЛОЖЕНИЕ А в центре, а название приложение снизу тоже центрировано.

**Comment by 5721309** [comment]
Я не уверен имел ли это в виду автор Issue: Как сделать так, чтобы в оглавлении все структурные главы (ВВЕДЕНИЕ, ЗАКЛЮЧЕНИЕ, ПРИЛОЖЕНИЕ) были указаны в верхнем регистре?

**Comment by einhander** [comment]
@ox42e9b А можно указать пункт ГОСТа 2001 года с этим требованием?

**Comment by einhander** [comment]
@Echobana 
> ПРИЛОЖЕНИЕ А в центре, а название приложение снизу тоже центрировано.

Сейчас так и есть, но я давно не смотрел, как выглядит этот стиль на данный момент.

**Comment by 5721309** [comment]
Как я понимаю, такого пункта в ГОСТ нет, но и пункта, строго регулирующего регистр этих элементов тоже нет. Я проблемы не создаю, её, я чувствую, создадут мне те, кто будет принимать работу. Хотелось бы научиться изменять регистр в случае чего.

**Comment by einhander** [comment]
@ox42e9b 
> я чувствую, создадут мне те, кто будет принимать работу.
 
Вот  ответ на претензии к вам по содержанию:
>Как я понимаю, такого пункта в ГОСТ нет

Если очень хочется, то самый простой вариант поменять названия в файле G7-32.sty
Или уже разбираться с кодом для создания содержания

Мое мнение капс в содержание выглядит убого.

**Comment by 5721309** [comment]
А как поменять слово ПРИЛОЖЕНИЕ? Его я не нашёл в этом файле
(EDIT: и в остальных)

**Comment by einhander** [comment]
@ox42e9b используется дефолтный макрос \appendixname

Меняется как то так, не проверял:
`````
 \addto\captionsrussian{%
  \renewcommand\appendixname{Дополнения}
  \renewcommand\appendixpagename{Доп.}
}

**Comment by 5721309** [comment]
Работает! Благодарю! Только appendixpagename undefined, но без него сойдёт.
