### ISSUE TITLE
Использование РПЗ - ошибка make

### ISSUE THREAD

**Issue by serious883** [rominf/latex-g7-32#110]
При запуске cmake .. и make получается вот такая картина:
**cmake ..**
`-- Found inkscape: /usr/bin/inkscape
-- Found dia: /usr/bin/dia
-- Found dot: /usr/bin/dot
-- Found makeindex: /usr/bin/makeindex
-- Found pdfcrop: /usr/bin/pdfcrop
-- Found gs: /usr/bin/gs
-- Found LATEX: /usr/bin/latex  found components: XELATEX PDFLATEX BIBTEX
-- Found Perl: /usr/bin/perl (found version "5.30.0")
-- Configuring done
-- Generating done
-- Build files have been written to: ...`
**make**
`Scanning dependencies of target latex-stage1
[  3%] Generating mirror/tex/inc/img/leonardo.png
[  6%] Generating mirror/tex/inc/svg/pic01.pdf

** (inkscape:25212): WARNING **: 01:47:04.349: Invalid option --export-type=pdf
make[2]: *** [CMakeFiles/latex-stage1.dir/build.make:92: mirror/tex/inc/svg/pic01.pdf] Error 1
make[1]: *** [CMakeFiles/Makefile2:245: CMakeFiles/latex-stage1.dir/all] Error 2
make: *** [Makefile:84: all] Error 2`

**Comment by einhander** [comment]
>  Invalid option --export-type=pdf

Скорее всего у вас старая версия inkscape. С версии 1.0 они поменяли параметры. Как вариант вы можете локально откатить  07ab52f или использовать другую систему сборки.
В конце концов можно собрать проект без системы сборки сделав нужные изображения руками.
Делать автоматизированное определение версии inkscape не считаю нужным.

**Comment by serious883** [comment]
Ну я не особо продвинутый unix пользователь, вижу ошибку, немного гуглю и, если не нахожу ответ, завожу issue :)

**Comment by einhander** [comment]
Альтернативная система сборки должна работать в вашем случае: https://github.com/latex-g7-32/latex-g7-32#%D0%B0%D0%BB%D1%8C%D1%82%D0%B5%D1%80%D0%BD%D0%B0%D1%82%D0%B8%D0%B2%D0%BD%D0%B0%D1%8F-%D1%81%D0%B8%D1%81%D1%82%D0%B5%D0%BC%D0%B0-%D1%81%D0%B1%D0%BE%D1%80%D0%BA%D0%B8
