### ISSUE TITLE
Процесс запущен: pdflatex -synctex=1 -interaction=nonstopmode "G2-105".tex

### ISSUE THREAD

**Issue by kolxz2** [rominf/latex-g7-32#112]
Здраствуйте, дорогие разработчики. Недавно познакомился с latex, всё нравиться, но вот не могу запустить ваш скрипт у себя на fedora. Начал собирать в TexStudio и выдаёт мне такую ошибку. Вроде всё что нужно установил, но почему-то не собирается проект. Подскажите пожалуйста.

**Comment by einhander** [comment]
Добрый день, для начинающих подготовлены инструкции с помощью систем сборки. Если хотите  собрать проект из Texstudio то основной файл rpz.tex. Учтите, что картинки готовятся системами сборки, для работы из Texstudio вам необходимо подготовить их самостоятельно, или взять любые другие с соответствующими названиями.
