### ISSUE TITLE
Подписи на английском / English support

### ISSUE THREAD

**Issue by detkov** [rominf/latex-g7-32#114]
Пишу НИР согласно ГОСТ, но на английском языке. Так как все названия и нумерация исходно здесь даны на кирилице, пришлось лезть внутрь переписывать на английские аналоги. 
Предлагаю добавить возможность выбора языка, как это сделано в библиографии.

**Comment by einhander** [comment]
Желание, конечно странное, в самом тексте ГОСТ прямо указано, как и что должно называться и на каком языке. Но препятствовать не буду, PR is welcome.
