### ISSUE TITLE
Перестало работать в pdflatex  Overleaf TexLive 2022

### ISSUE THREAD

**Issue by fram1984** [rominf/latex-g7-32#115]
Пользовался шаблоном в Overleaf и заметил, что с выходом новой версии TexLive компиляция стала генерировать ошибки типа "Argument of � has an extra }."

**Comment by fram1984** [comment]
В общем проблема оказалась в параметре кодировки utf8 после его удаления из sty файла и из параметров документа, все начинает работать.

**Comment by idamir** [comment]
Из какого файла? В какой строке?

**Comment by artyommatveev** [comment]
У меня такой же вопрос - где это необходимо исправить? В .sty файлах я вообще на нашёл ничего связанного с utf-8 (разве только в комментариях).

**Comment by idamir** [comment]
Замечу, что действительно перестали отчёты собираться в локальной установке TexLive 2022. Сборка в TexLive 2020 работает без проблем. Ошибка проявляется при добавлении Приложения (при формировании заглавия Приложения) и дублируется при сборке Оглавления.
В итоге формируются названия
> ПРИЛОЖЕНИЕ
> ИМЯ ПРИЛОЖЕНИЯ 1

> ПРИЛОЖЕНИЕ
> ИМЯ ПРИЛОЖЕНИЯ 2

вместо

> ПРИЛОЖЕНИЕ А
> ИМЯ ПРИЛОЖЕНИЯ 1

> ПРИЛОЖЕНИЕ Б
> ИМЯ ПРИЛОЖЕНИЯ 1

Предложение:
в файле G2-105.sty команду \Asbuk определить вместо
`\StrChar{АБВГДЕЖИКЛМНПРСТУФХЦШЩЭЮЯ}`
строкой типа
`\StrChar{\CYRA\CYRB\CYRV.....\CYRYA}`
Предварительные тесы показывают, что помогает.

**Comment by idamir** [comment]
А ещё лучше, взять определение \Asbuk и \asbuk из пакета babel, тем более он используется:
`/usr/share/texlive/texmf-dist/tex/generic/babel-russian/russianb.ldf`

**Comment by einhander** [comment]
> Замечу, что действительно перестали отчёты собираться в локальной установке TexLive 2022

Xelatex или pdflatex?

**Comment by idamir** [comment]
pdflatex

**Comment by artyommatveev** [comment]
Мой вопрос, в свою очередь, касался сборки в Overleaf. Было бы хорошо, если бы там тоже работало. Сейчас же я локально просто редактирую файлы в TeXstudio, сохраняю их, а потом делаю сборку через docker каждый раз. То есть в TeXstudio не запускаю компиляцию и не пользуюсь там просмотром документа.

**Comment by einhander** [comment]
>Мой вопрос, в свою очередь, касался сборки в Overleaf.

Переключите на xelatex, в Overleaf обновили TexLive до 2022.

**Comment by artyommatveev** [comment]
> > Мой вопрос, в свою очередь, касался сборки в Overleaf.
> 
> Переключите на xelatex, в Overleaf обновили TexLive до 2022.

Если ничего не менять в [изначальном](https://www.sharelatex.com/project/54885f204b9308be064f025e) примере, а только переключиться на XeLaTeX (TeX Live 2022), то появляются другие ошибки: "Command \defineshorthand already defined.", "Command \shorthandon already defined.", "Package polyglossia Error: Unknown direction ." и т.д. При удалении параметра кодировки utf8x из объявления класса документа в rpz.tex, ошибки аналогичные. В .sty файлах кодировку utf-8 не нашёл. Это я имею в виду [данную](https://github.com/latex-g7-32/latex-g7-32/issues/115#issuecomment-1367281083) рекомендацию.

**Comment by einhander** [comment]
@idamir 
>Предварительные тесы показывают, что помогает.

Предварительные тесты показывают, что эти строчки сейчас там вообще сейчас не нужны. Можно их закомментировать  и проверить, на локальной установке пример собирается и с pdflatex и с xelatex.

**Comment by idamir** [comment]
Их удаление нарушает комментарий
`% GOST 7.32 p. 6.4.6 excluded letters ё, з, й, о, ч, ъ, ы, ь..`

П. 6.4.6 ГОСТ 7.32-2017 действительно требует эти буквы исключить:
https://cs.msu.ru/sites/cmc/files/docs/2021-11gost_7.32-2017.pdf
> 6.4.6 Внутри пунктов или подпунктов могут быть приведены перечисления. Перед каждым элементом перечисления следует ставить тире. При необходимости ссылки в тексте отчета на один из элементов  перечисления вместо тире ставят строчные буквы русского алфавита со скобкой, начиная с буквы «а» (за исключением букв ё, з, й, о, ч, ъ, ы, ь). Простые перечисления отделяются запятой, сложные — точкой с запятой.
> При наличии конкретного числа перечислений допускается перед каждым элементом перечисления ставить арабские цифры, после которых ставится скобка.
> Перечисления приводятся с абзацного отступа в столбик.

Определения \Asbuk и \asbuk из пакета babel в
`/usr/share/texlive/texmf-dist/tex/generic/babel-russian/russianb.ldf` 
включают эти буквы.

**Comment by einhander** [comment]
Действительно проглядел З, О и Ч
Тогда действительно можно взять из babel типа такого решения:
````
\def\Asbuk#1{\expandafter\russian@Alph\csname c@#1\endcsname}
\def\russian@Alph#1{\ifcase#1\or
    А\or Б\or В\or Г\or Д\or Е\or Ж\or
    И\or К\or Л\or М\or Н\or 
    П\or Р\or С\or Т\or У\or Ф\or Х\or
    Ц\or Ш\or Щ\or Э\or Ю\or Я\else\@ctrerr\fi}
````
Работает в xelatex и pdflatex.

**Comment by afaikiac** [comment]
> Работает в xelatex и pdflatex.

У меня не заработало с pdflatex, может что-то не так делаю.

Был бы благодарен, если бы среди возможных решений выбрали какое-то одно рабочее и красивое и сделали коммит в `7.32-2017-dev` ветку.

**Comment by einhander** [comment]
>У меня не заработало с pdflatex, может что-то не так делаю.

Все изменения надо тестировать, поэтому  от коммита воздержался. Быстро тестировал только на мастере, до 2017-dev не добрался. 

Всё же тут как выяснилось разные ошибки поэтому с ошибки с реализацией Asbuk лучше обсуждать в #120, а эту тему оставить под Overleaf.

**Comment by idamir** [comment]
В чём проблема переоткрытия?

**Comment by einhander** [comment]
В Overleaf работает? Когда я проверял, ошибка была другая.
`Argument of � has an extra }`. С фиксом не проверял.

**Comment by idamir** [comment]
Эта же ошибка была на локальном texlve 2022, и она связана была с нумерацией приложений.

**Comment by einhander** [comment]
@idamir подтверждаете, что в Overleaf работает?

**Comment by idamir** [comment]
Ругается на \secdef в G2-105.sty

**Comment by idamir** [comment]
В Overleaf всё ещё не работает. Ругается на объявления `\chapter`, `\{sub}section`.

**Comment by einhander** [comment]
@idamir, @afaikiac проверяйте, должно фиксить #115. 

@fram1984 прав:
> В общем проблема оказалась в параметре кодировки utf8 после его удаления из sty файла и из параметров документа, все начинает работать.
