### ISSUE TITLE
счётчики totfigures и tottables обновляются неправильно если нумерация сквозная 

### ISSUE THREAD

**Issue by idamir** [rominf/latex-g7-32#116]
Актуально для ветки 2017. Для master ветви надо проверять.

В preambile.inc .tex комментируем три команды для сквозной нумерации.
`%\EqInChapter % формулы будут нумероваться в пределах раздела`
`%\TableInChapter % таблицы будут нумероваться в пределах раздела`
`%\PicInChapter % рисунки будут нумероваться в пределах раздела`

Теперь если в предыдущих разделах (chapter) имеются рисунки, то при начале нового раздела к счётчику totfigures добавляется значение figure. В конце документа происходить то же самое. Таким образом значение totfigures множится. Для tottables аналогично.

Пример.
chapter1 - 3 рисунка
chapter2 - 2 рисунка
chapter3 - 1 рисунок
chapter4 - 0 рисунков

Ожидаем: AtEndDocument к totfigures (ещё равен 0) добавляется 3+2+1=6, итого totfigures=6.

Имеем:
chapter1 - figures=3
totfigures =+ 3 -> totfigures=3
chapter2 - figures=3+2=5
totfigures =+ 5 -> totfigures=8
chapter3 - figures=5+1=6
totfigures =+ 6 -> totfigures=14
chapter4 - figures=6
totfigures =+ 6 -> totfigures=20

Итого totfigures=20 вместо 6.

Предложение: в файле G2-105.sty
при определении 
`\newcommand\chapter{`
строчку
`{\addtocounter{totfigures}{\value{figure}}}%`
перенести после 
`\if@figuresonchapter%`
Тогда значение totfigures будет увеличиваться корректно перед сбросом figure в 0.

**Comment by einhander** [comment]
PR welcome! Я подтвержу. Главное, чтобы в обоих случаях отображалось корректно.
