### ISSUE TITLE
Ошибка при запуске через docker

### ISSUE THREAD

**Issue by Naymoll** [rominf/latex-g7-32#127]
Комманда `docker run --volume "$latex_g7_32":/doc latex-g7-32` завершается с ошибкой без создания каких-либо файлов, кроме пустой папки `results`

Linux: 6.1.25-1-MANJARO (64-bit)

```
[100%] Built target makeindex
This is BibTeX, Version 0.99d (TeX Live 2022/Debian)
The top-level auxiliary file: rpz.aux
The style file: ugost2008.bst
Database file #1: rpz.bib
"\" can't start a style-file command---line 2611 of file ugost2008.bst
 :
 : \endinput
(Error may have been on previous line)
(There was 1 error message)
make[2]: *** [CMakeFiles/bibtex.dir/build.make:70: CMakeFiles/bibtex] Error 2
make[1]: *** [CMakeFiles/Makefile2:115: CMakeFiles/bibtex.dir/all] Error 2
make: *** [Makefile:91: all] Error 2
+ cp rpz.pdf ..
cp: cannot stat 'rpz.pdf': No such file or directory
```  

Вот полный лог запуска
[run.log](https://github.com/latex-g7-32/latex-g7-32/files/11386604/run.log)

**Comment by afaikiac** [comment]
Это потому что репозиторий склонировали, а сабмодуль со стилями — нет. Lack of documentation.

Склоноровать сабмодули можно с самого начала:

```
git clone --recurse-submodules https://github.com/latex-g7-32/latex-g7-32.git
```

или уже после:

```
git submodule init
git submodule update
```

Если Вам не нужны скрипты сборки, пока можно использовать мой форк https://github.com/afaikiac/latex-g7-32.git

**Comment by Naymoll** [comment]
Работает. Закрываю тогда
