### ISSUE TITLE
How can I change the language to English?

### ISSUE THREAD

**Issue by albas99** [rominf/latex-g7-32#137]
I've changed the option in the babel import from Russian to English but it's still rendering in Russian, is there anywhere else where the babel package has been used apart from the `rpz.tex` file? How can I change the language to English?

**Comment by einhander** [comment]
Hello @albas99 
The government standard GOST 7.32 declare russian as only language used in documents. Thus this class template can be used only with russian language. The russian names of chapters and so on hardcoded in *.sty files. If you are skilled LaTeX user you can change them in *.sty files and create your own fork.

**Comment by albas99** [comment]
Oh, okay. Thanks
