### ISSUE TITLE
Докер не собирается из-за битой ссылки на шрифты

### ISSUE THREAD

**Issue by mbait** [rominf/latex-g7-32#139]
http://astralinux.ru/information/fonts-astra/font-ptastra-serif-ver1003.zip выдаёт 404, замена на https не помогает.

**Comment by einhander** [comment]
Шрифты теперь лежат тут https://www.paratype.ru/fonts/pt/pt-astra-serif?tab=packages и скачиваются по индивидуальным ссылкам. Можно положить шрифты в саму репу, как они раньше и лежали.
