### ISSUE TITLE
В Telive 2018, с pdflatex не собирается.

### ISSUE THREAD

**Issue by einhander** [rominf/latex-g7-32#82]
В Telive 2018 что-то поменяли, теперь с pdflatex не собирается((

**Comment by dvarubla** [comment]
Мне удалось собрать лишь убрав `\usepackage{upquote}`

**Comment by dvarubla** [comment]
Можно даже оставить `upquote`, но убрать `mathtext`, тогда вроде нормально. Все равно кириллица в формулах [не работает]( https://github.com/latex-g7-32/latex-g7-32/issues/54).

**Comment by einhander** [comment]
Предлагаю убрать убрать `mathtext`.

**Comment by dvarubla** [comment]
@einhander я за, если у вас при этом собирается, конечно. Может, я что-то не учёл.

**Comment by einhander** [comment]
У меня собирается и работает без `mathtext`.
